# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: arm_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 100 #ori: 300
  cycle_time_error_threshold: 0.03 #ori: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - simple_gripper_gripper_finger1_joint
  sim_control_mode: 1  # 0: position20230815, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: my_joint_to_cartesian_controller/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    gains:
      shoulder_pan_joint:
        p: 1000
        d: 50
        i: 10
        i_clamp: 100
      shoulder_lift_joint:
        p: 5000
        d: 30
        i: 100
        i_clamp: 400
      elbow_joint:
        p: 5000
        d: 50
        i: 10
        i_clamp: 100
      wrist_1_joint:
        p: 200
        d: 20
        i: 10
        i_clamp: 100
      wrist_2_joint:
        p: 100
        d: 10
        i: 0.1
        i_clamp: 100
      wrist_3_joint:
        p: 10
        d: 1
        i: 0.1
        i_clamp: 100
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - simple_gripper_gripper_finger1_joint
  - name: joint_position_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
